---
-  hosts: localhost
   any_errors_fatal: true
   gather_facts: no

  tasks:
  - name: Update the machine
    tags: upd
    yum:
      update_only: yes


  - name: Install General Essential packages
    tags: essentials
    yum: 
      name: 
        - nano
        - net-tools
        - tcpdump
        - nmap
        - wireshark
        - git
        - wget
        - iproute
        - psmisc
        - yum-utils
        - chrony
        - telnet
        - iptables-services
        - conntrack
        - gcc
        - bridge-utils
      state: present

  - name: Set the timezone.
    tags: NTP
    shell: |
      timedatectl set-ntp true
      timedatectl set-timezone Europe/Berlin

  - name: Edit "/etc/sysctl.conf" file
    tags: sysctl
    lineinfile:
      path: /etc/sysctl.conf
      line: " net.ipv4.ip_forward = 1 \n  net.ipv6.conf.all.forwarding = 1 \n net.ipv4.conf.all.accept_redirects = 0  \n net.ipv4.conf.all.send_redirects = 0 "    

  - name: Create Networking script 
    ansible.builtin.template:
      src: /root/lw4o6-automation/files/client-networking.txt
      dest: /root/networking.sh
      owner: root
      mode: '755'
