---
-  hosts: localhost
   any_errors_fatal: true
   gather_facts: no

   tasks:
   - name: Update the machine
     tags: upd
     yum:
       update_only: yes


   - name: Install General Essential packages
     tags: essentials
     yum: 
       name: 
         - nano
         - net-tools
         - tcpdump
         - nmap
         - wireshark
         - git
         - wget
         - iproute
         - psmisc
         - yum-utils
         - chrony
         - telnet
         - iptables-services
         - conntrack
         - gcc
         - bridge-utils
         - hping3
       state: present

   - name: Install several packages in case of deleting iptables
     tags: iptables
     yum: 
       name: 
         - iptables
         - iproute
         - dhclient
         - plymouth
         - initscripts
         - kbd
         - kexec-tools
         - dracut
         - firewalld
         - iptables-services
         - mlocate
       state: present


   - name: Set the timezone.
     tags: NTP
     shell: |
       timedatectl set-ntp true
       timedatectl set-timezone Europe/Berlin


   - name: Edit "/etc/sysctl.conf" file
     tags: sysctl
     lineinfile:
       path: /etc/sysctl.conf
       line: " net.ipv4.ip_forward = 1 \n  net.ipv6.conf.all.forwarding = 1 \n net.ipv4.conf.all.accept_redirects = 0  \n net.ipv4.conf.all.send_redirects = 0 "  

   - name: Clone snabb-repo
     tags: sanbb
     git:
       repo: https://github.com/eugeneia/snabb.git
       single_branch: yes
       version: lwaftr-tutorial
       dest: /root/
       clone: yes
       update: yes

   - name: Play around withing the repo 
     tags: snabb
     shell: make
     args:
       chdir: /root/snabb
       

   - name: Create 'lwaftr-start.conf' file 
     tags: snabb
     ansible.builtin.template:
       src: /root/lw4o6-automation/files/lwaftr.txt
       dest: /root/snabb/lwaftr-start.conf
       owner: root
       mode: '755'
       
