---
- name: Configure lwAFTR
  hosts: localhost
  gather_facts: no
  connection: local


  tasks:
  - name: Update the machine
    tags: upd
    yum:
      update_only: yes

  - name: Install General Essential packages
    tags: essentials
    yum: 
      name: 
        - nano
        - net-tools
        - tcpdump
        - nmap
        - wireshark
        - git
        - wget
        - iproute
        - psmisc
        - yum-utils
        - chrony
        - telnet
        - iptables-services
        - conntrack
        - gcc
        - make
        - bridge-utils
        - numactl
      state: present

  - name: Remove 'irqbalance' package, coz it affects the Performance
    yum: 
      name: irqbalance
      state: absent

  - name: Set the timezone.
    tags: NTP
    shell: |
      timedatectl set-ntp true
      timedatectl set-timezone Europe/Berlin

  - name: Clone snabb-repo
    tags: sanbb
    git:
      repo: https://github.com/eugeneia/snabb.git
      single_branch: yes
      version: lwaftr-tutorial
      dest: /root/snabb
      clone: yes
      update: yes

  - name: Compile everything.
    tags: snabb
    shell: make
    args:
      chdir: /root/snabb

  - name: Create 'lwaftr-start.conf' file 
    tags: snabb
    ansible.builtin.template:
      src: /root/lw4o6-automation/files/lwaftr.txt
      dest: /root/snabb/lwaftr-start.conf
      owner: root
      mode: '755'

  - name: Create Networking file 
    tags: snabb
    ansible.builtin.template:
      src: /root/lw4o6-automation/files/lwaftr-networking.txt
      dest: /root/networking.sh
      owner: root
      mode: '755'
